#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

py_compile "$PYFILE" && mv "__pycache__/$PYFILE.cpython-*.pyc" "$PYFILEc" && rm -rf "__pycache__"
echo "Compiling $PYFILE ..."
